import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState, useEffect } from 'react'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'



export default function Home() {

  const [names, setNames] = useState([])
  const fetchHello = async () => {
    const response = await fetch('api/hello');
    const data = await response.json();
    console.log(data);
    setNames(data);
  }

  useEffect(() => {
    fetchHello();
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main >
        
      </main>

    </div>
  )
}
